### ISSUE TITLE
У вас здесь написано Java 7, а ниже Java 11

### ISSUE THREAD

**Issue by coursar** [loriddle/Bonus-Service#9]
Уберите это:
https://github.com/loriddle/Bonus-Service/blob/f04ae09130ab014c01c7abca254cbca8890a0189/pom.xml#L10-L21

Оставьте это:
https://github.com/loriddle/Bonus-Service/blob/f04ae09130ab014c01c7abca254cbca8890a0189/pom.xml#L23-L27

**Comment by loriddle** [comment]
Исправлено в f1430bef1ed9b318447ab617743cae3dcfe2e846

**Comment by coursar** [comment]
Закрывайте сразу сообщением коммита
